### ISSUE TITLE
IE

### ISSUE THREAD

**Issue by jessefrye** [f1337/metafas3#1]
Having a problem in IE v3.2alpha. Can you fix pls!

**Comment by bcelenza** [comment]
Where's the like button here?!

**Comment by jessefrye** [comment]
Haha!!

From:  Brian Celenza
<reply+i-2419816-81818b101d8057ac90ea5ebc2026ec960739fb2c-127787@reply.githu
b.com>
Date:  Thu, 1 Dec 2011 13:53:59 -0800
To:  Jesse Frye teamlinx@gmail.com
Subject:  Re: [metafas3] IE (#1)

Where's the like button here?!

---

**Comment by ElliotChong** [comment]
Metafas3 isn't working in my AS2 banner, why are you releasing broken softwares? Fix plz!!1

**Comment by f1337** [comment]
Did the three of you get together on Skype and decide to punk me? :P

**Comment by bcelenza** [comment]
Nope! We're just good like that :)

**Comment by f1337** [comment]
Punx. Hey, check this out:

https://github.com/RestKit/RestKit/pull/453

;)
